language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

# Also run these python versions with a specific distribution:
matrix:
  include:
    - python: 3.3
      dist: trusty

# command to install dependencies
install: "python setup.py install"
# command to run tests
script: py.test